### PR TITLE
Re-add commons-collections3 and add to root path

### LINKED ISSUE #4435: 3.10.0 JMS Sender needs common-collections-3 but only commons-collections4 is bundled
When i try to use the JMS Sender in a destination i get a runtime exeception : 

java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap

The class is from commons-collections-3 and not available in commons-collections4. It is used by commons-beanutils (PropertyUtilsBean).

```java
...
import org.apache.commons.beanutils.expression.Resolver;
import org.apache.commons.collections.FastHashMap;
import org.apache.commons.logging.Log;
...
```

Adding commons-collections-3 to the lib directories doesn't help.

Stacktrace:
```java
ERROR 2020-11-30 13:34:47,139 [Channel Dispatch Thread < HTTP Receiver Thread on mia (5752042d-6079-41e8-8edd-730debaa8505) < qtp270665618-78] com.mirth.connect.donkey.server.channel.Channel: Error processing message in channel mia (5752042d-6079-41e8-8edd-730debaa8505).
com.mirth.connect.donkey.server.channel.ChannelException: 
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1289)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:170)
	at com.mirth.connect.connectors.http.HttpReceiver$RequestHandler.handle(HttpReceiver.java:381)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:560)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
	at com.mirth.connect.donkey.server.channel.Channel.handleDestinationChainThrowable(Channel.java:1872)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1807)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1267)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:963)
	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:935)
	at org.apache.commons.beanutils.BeanUtils.setProperty(BeanUtils.java:454)
	at com.mirth.connect.util.BeanUtil.setProperties(BeanUtil.java:24)
	at com.mirth.connect.connectors.jms.JmsDispatcher.getJmsConnection(JmsDispatcher.java:286)
	at com.mirth.connect.connectors.jms.JmsDispatcher.send(JmsDispatcher.java:140)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:888)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:518)
	at com.mirth.connect.donkey.server.channel.DestinationChain.doCall(DestinationChain.java:121)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:63)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1805)
	... 23 more
```

### PR DESCRIPTION
**Pull request by tonygermano**
This version of the library was removed in mirth 3.10.0 when
collections4 was included. However, commons-beanutils has a dependency
on the 3.x version. At that time, commons-beanutils was also added
to the root class path, so its dependencies must also be added.

Fixes nextgenhealthcare/connect#4435

### CODE REVIEW

**Comment by ChristopherSchultz** [comment]
Yes, please.

**Comment by cturczynskyj** [comment]
We actually created our own internal fix for this (similar but with a few more changes) so I'm going to close this pull request since the fix is coming in the next release.

**Comment by ChristopherSchultz** [comment]
Can you be more specific about the definition of _next release_?

**Comment by pladesma** [comment]
It will be in the next major or minor release, which should be released in the coming weeks.

**Pull request closed without merging**
