### PR TITLE
Fix java.lang.NoClassDefFoundError: java/sql/Driver when running on J…

### PR DESCRIPTION
**Pull request by dfauraz**
Fix java.lang.NoClassDefFoundError: java/sql/Driver when running on JDK9+
Details see: https://github.com/nextgenhealthcare/connect/discussions/5079

### CODE REVIEW

**Comment by jonbartels** [comment]
Referencing the system classloader when initializing the isolated class loader defeats the purpose of the isolated classloader.

The original purpose of the isolated classloader was to prevent a channel using libraries from the system classpath to avoid conflicts with different library versions that the system classpath has.

Some old discussion on this topic:
* https://github.com/nextgenhealthcare/connect/issues/4075
* https://github.com/nextgenhealthcare/connect/search?q=isolated+classloader&type=issues
* https://forums.mirthproject.io/search?q=isolated+classloader&searchJSON=%7B%22keywords%22%3A%22isolated+classloader%22%7D

**Comment by dfauraz** [comment]
Hi! I am unsure about the right solution.

What I can say is:
* we need to use a resource because we run on a Mirth Appliance and cannot add JARS otherwise
* we just want to add an official JDBC driver to our channel, for FileMaker in this particular case
* because the driver needs the class java.sql.Driver as parent, it fails on channel deployment
* the exact same code fails on JDK 11 where it works on JDK 8 so for us it's a regression/bug
* we tried adding some --add-modules like those in mcservice-java9+.vmoptions, to no avail

My impression is that on JDK11 (in fact starting with JDK9), you will have problems with the current resource implementation, because you will need to handle JVM modules like java.sql as well.

Finally, what would be the recommended solution in our case ? add rt.jar to the resource ? That sounds a bit drastic !
Probably more go back to JDK 8, if possible on Mirth Appliance (I need to check)

**Comment by jonbartels** [comment]
> we need to use a resource because we run on a Mirth Appliance and cannot add JARS otherwise

Using Resource Directories is the correct way to manage custom JARs.

> we just want to add an official JDBC driver to our channel, for FileMaker in this particular case

Hmm the best way to do this would be to use: https://docs.nextgen.com/bundle/Mirth_User_Guide_41/page/connect/connect/topics/c_editing_database_drivers.html

However I think that expects the DB drivers in `server-lib`.

Can you show your channel dependencies screen please? I wonder if you should also include the `Default Resource` to fix the issue.

Finally - Even if a code change in a PR isn't the best solution for your problem, I think it is awesome that you opened the code and sent in a PR! I like seeing people hacking on Mirth Connect!

**Comment by dfauraz** [comment]
Yes of course, you need the JAR in the classpath.
On the appliance server-lib is not accessible, only resources.
In fact we use the Default Resource already, to no avail.

The problem is the way the isolated classloader is built.

It's quite easily reproducible:
* find a custom JDBC driver (any driver will do)
* use it in your channel db receiver/sender
* deploy the JDBC driver in a resource (for example Default Resource)
* run on JDK 8 and deploy the channel => no problem
* run on JDK11 and deploy the channel => NoClassDefFoundError: java.sql.Driver

**Comment by pladesma** [comment]
Closing this PR as per Jon B's initial response. Feel free to create an issue if you think this is a defect or create a discussion topic.

**Comment by dfauraz** [comment]
So the only way to run a channel with a JDBC driver that is not shipped with Mirth Connect is to run on Java 8 : not really future proof ! :(

**Pull request closed without merging**
