### PR TITLE
EqualsBuilder.reflectionEquals supports recursive check now, nested p…

### LINKED ISSUE #4989: [BUG] Connector properties nested changes are not detected
**Describe the bug**
A clear and concise description of what the bug is. Is this consistently reproducible?

**To Reproduce**
Setup steps (if required). Example:
i.e. TransmissionModeProperties class has FrameModeProperties field, it's also a class. If any property of this nested class changed it's not being detected with simple use of `EqualsBuilder.reflectionEquals` in the current NextgenConnect.

A sample connector I've developed recently and encountered this issue. In below branch for TCP Connector there's IsTLS Enabled and send Auto ACK checks. Even these checks are part of the connector properties (nested), the change is not saved, and not appear as revision change.
https://github.com/CSCONNECT/connect/commits/development 

**Expected behavior**
All nested serializable properties need to be considered as change and cause revision change.  `EqualsBuilder.reflectionEquals` has an an overridden method to support this now.

**Actual behavior**
Only direct property of the connector is detected as a change but not nested props.

**Environment (please complete the following information):**
 - Windows 10, JDK8

**Workaround(s)**
As workaround any other simple direct property of connector can be changed and channel saved to enforce revision change.

**Additional context**
A property can be introduced FrameModeProperties  and only changing it in the screen will not work. I believe nested checking is a better approach and it can reduce checking deep property changes in the code. 

Related to #4950 @pladesma based on your request I created this issue.

### PR DESCRIPTION
**Pull request by davutg**
…roperties' changes can be checked this way

### CODE REVIEW

**Comment by davutg** [comment]
This commit helps nested properties change detection. 
i.e. `TcpReceiverProperties` has private Object fields such as instance of `ListenerConnectorProperties`, `SourceConnectorProperties`.  These object fields' own field changes were not causing a revision change for me. 
This deep check gonna check nested fields and cause a revision change.

**Comment by pladesma** [comment]
Thanks for the pull request. Can you please create a related BUG Github issue and link it to this PR? In the issue, can you provide steps to reproduce the issue? We would just like more information about the problem that is being solved by this PR.

**Review by cturczynskyj — CHANGES_REQUESTED** [review]
Instead of making this change (which could impact a lot of other code), it would be better to, instead, just remove the equals method in FrameModeProperties and change the equals method in TransmissionModeProperties to call EqualsBuilder.reflectionEquals. This is untested, but should be ok, but to be sure we would also need some unit tests that prove that the behavior has not changed in FrameModeProperties, or any subclass of FrameModeProperties (maybe just MLLPModeProperties).

**Review by davutg — COMMENTED** [review]
formatting is okay. I believe you found my extra comments a little dirty :)

**Comment by pladesma** [comment]
I'm not sure what you meant by your last comment, but please see @cturczynskyj 's last comment for the changes that we're requesting in order to merge this PR. Thanks.

**Comment by davutg** [comment]
@pladesma dismiss my previous comment. I thought the way I put line by line extra comments were ugly while reviewing my code... Regarding this PR, the way reflectionEquals were working was not supporting deep checks. Apache added this in time according to SO post I shared earlier. So, to the best of my understanding there were workarounds applied in order to support nested/deep object equality checking. @cturczynskyj's concern is, this might work nicely, or cause some behavioural changes in overall the app. Without a comprehensive test we can't know... I understand this and leaving it to you..

**Comment by pladesma** [comment]
We appreciate the work you've put into the pull request, but without tests to prove that this change doesn't affect current behavior, we can't merge this. Feel free to open pull requests in the future. Thank you.

**Pull request closed without merging**
