### PR TITLE
Handle transport/schema_info tables existing/not existing

### PR DESCRIPTION
**Pull request by timpwbaker**
This commit proposes the following update:

In the first postgres migration, only try to drop transport if it exists, and only try to create schema_info if it does not exists.

We have recently encountered an issue where if mirth is not shut down correctly these tables can be left in a bad state and the following errors occur on boot:

ERROR 2023-10-30 17:37:39.962 [Main Server Thread] com.mirth.connect.server.Mirth: Failed to migrate database schema
```
com.mirth.connect.model.util.MigrationException: Failed to execute script: postgres-0-1.sql
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:103) ~[mirth-server.jar:?]
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:86) ~[mirth-server.jar:?]
	at com.mirth.connect.server.migration.LegacyMigrator.migrate(LegacyMigrator.java:23) ~[mirth-server.jar:?]
	at com.mirth.connect.server.migration.ServerMigrator.migrate(ServerMigrator.java:78) ~[mirth-server.jar:?]
	at com.mirth.connect.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:96) ~[mirth-server.jar:?]
	at com.mirth.connect.server.Mirth.startup(Mirth.java:319) ~[mirth-server.jar:?]
	at com.mirth.connect.server.Mirth.run(Mirth.java:168) ~[mirth-server.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: table "transport" does not exist
```

Similar for schema_info, although I've closed that terminal window unfortunately.

The solution was to create an empty transport table with any old column:
```
CREATE TABLE transport (
    foo integer
);
```

I also dropped the table schema_info, got an error later in the migrations saying schema_info didn't exist, again, sorry, I've lost this stack trace.

I then recreated it:

```
CREATE TABLE schema_info (
    version text
);

INSERT INTO schema_info (version) VALUES ('4.4.0');
```

The application then booted.

I realise this is part bug report part PR. But I genuinely feel like I've aged 10 years in the last 2 hours, so I wanted to push something up. I'm 99% sure this is to do with shutting down unsafely, but on the off chance it's something to do with a mirth upgrade...

### CODE REVIEW

**Comment by jonbartels** [comment]
This does seem like an environmental issue with the DB in an inconsistent state or a config pointing to the wrong DB. 

What is the general issue you were working on when you found this problem? Were you doing an upgrade or migration?

**Comment by timpwbaker** [comment]
Hi, nope, no upgrade or migration. An unsafe restart of the app is the only thing that happened today. I wasn't actually working on anything to do with mirth, I restarted all the services running on the VM for a totally separate reason. 

Definitely the right database, no config changes and when I went through the above the application booted, again with no config changes.

**Comment by timpwbaker** [comment]
I realise my comment above said "on the off chance it's something to do with a mirth upgrade", I said this because we run the latest docker image and I wasn't sure if it had updated without me noticing. It hadn't, I have since checked this.

**Comment by jonbartels** [comment]
Which container image? The one from https://github.com/nextgenhealthcare/connect-docker ?

I can't look right now, but what would be relevant here is learning how Mirth decides to run a particular DB migration or not. The likely explanation is that some tracking object wasn't stored or read properly during the unclean shutdown/restart. The problem might not be the script but the logic that decided to run the script.

**Comment by timpwbaker** [comment]
Yes, that's the docker image I'm using, version 4.4.0. 

Interesting comment on deciding whether to run the migrations or not, I had assumed they all got run. Definitely sounds like a reasonable probability, as the two tables that were problematic were either not there but should be, or should be but not there.

**Pull request closed without merging**
