### PR TITLE
create tls 1.2 preffered profiles

### PR DESCRIPTION
**Pull request by ssnath2**

### CODE REVIEW

**Comment by narupley** [comment]
So the main thing is that there are TWO new sets of cipher suites (BCP and "non-downgrading" BCP) right? And these are only really valid for DICOM right? If that's the case I don't think it makes sense to add new lists to mirth.properties for this, it seems like the changes should be contained only to the DICOM connectors.

The next thing is... we do have an SSL Manager extension that is supported on all of our TCP-based connectors (like the DICOM Listener/Sender). With that extension you have the ability to fine-tune exactly what protocols / cipher suites you want to have enabled on each connector. It sounds like with the SSL Manager this feature should already be supported, correct?

Obviously that doesn't help if you are only using the open source distribution though, so I understand wanting a solution here. We'll be looking into this and use your work here as a reference point.

**Comment by pladesma** [comment]
Closing as per Nick's comments.

**Comment by tonygermano** [comment]
@pladesma @twest-mirthconnect to clarify, are you still looking into a solution to make these improvements to the open-source DICOM plugin? That comment was made over two years ago, and it's recently been announced that a new commercial DICOM extension is in the works.

It would be good to know if there are no intentions to make further improvements to the existing open-source DICOM connector.

**Comment by twest-mirthconnect** [comment]
The primary focus is commercial but some of the features will surely have some impact on the open-source product. But to be clear, we are only working on a new commercial extension.

**Pull request closed without merging**
